spring:
  datasource:
    url: jdbc:tibero:thin:@43.201.40.39:8629:tibero
    username: dajoba
    password: dajoba
    driver-class-name: com.tmax.tibero.jdbc.TbDriver

  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug  #로거로 찍음
    org.hibernate.type: trace